language: ruby
rvm:
- 2.1.2

before_script:
 - chmod +x ./script/cibuild.sh # or do this locally and commit

script: ./script/cibuild.sh

# branch whitelist
branches:
  only:
  - master     # test the master or gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
