# Site wide configuration

title: 'Ministep'
header-img: "img/autumn2.jpg"
description: 'Live and learn'
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
permalink: none
paginate: 8
timezone: Asia/Shanghai


# Site owner
owner:
  name: "Ministep"
  email: minisstep@163.com
  twitter:
    googleAnaly:
    config: true
    id: UA-71341085-1
  google:
    ad-client:
    ad-slot:
  bio: "learn more"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
