permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true
timezone: Asia/Shanghai

kramdown:
  input: GFM

# 作者信息
author: 
  name: minisstep
  email: minisstep@163.com
  link: http://www.minisstep.com
  weibo: http://weibo.com/u/2810541501
  github: https://github.com/minisstep

# 站点信息
title: minisstep
description: 唯有强壮的体魄和进取的心才能勇往直前
url: http://www.minisstep.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: images/favicon.png
favicon: images/favicon.ico

# google analytics 设置
ga:
  id: UA-71930253-1
  url: www.minisstep.com

# disqus 设置
disqus:
  shortname: minisstep
