# Site settings
title: Ministep
header-img: "img/autumn2.jpg"
tagline: "minisstep"
description: "坚持不懈，方能成功"
baseurl: ""
url: "minisstep.github.io"
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Ministep"
  email: minisstep@163.com
  bio: "强生健体和不断学习，才能永葆活力"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: Minisstep
twitter_username:  Minisstep
github_username:  Minisstep
facebook_username:  Minisstep
weibo_username:  Minisstep
zhihu_username:  Minisstep

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ministep"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : ministep
  disqus :
      short_name : ministep


#Analytics and webmaster tools stuff goes here
googleAnaly:
  config: true
  id: UA-71341085-1
#Links to include in footer navigation

